spring:
  datasource:
    url: jdbc:mysql://localhost:3306/da_chuang?characterEncoding=utf-8
    username: root
    password: MYSQLtxjjzyzqbx123#
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      # 用来指定服务器端文件大小的限制
      max-file-size: 300MB
      # 用来指定客户端文件大小的限制
      max-request-size: 300MB
#      fileLocation: static/files
#  webservices:
#     allowed-origins: 'http://127.0.0.1:5500/'
file:
  location: D:/大创/网站/ #自定义上传文件本地保存路径
server:
  port: 8080
mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml


