spring:
  datasource:
    url: jdbc:mysql://localhost:3306/da_chuang?characterEncoding=utf-8
    username: root
    password: MYSQLtxjjzyzqbx123#
    driver-class-name: com.mysql.cj.jdbc.Driver
server:
  port: 8888
mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
